spring.application.name=SpringOuathSecurity1
spring.security.oauth2.client.registration.github.client-id=//eth client id takaychi 
spring.security.oauth2.client.registration.github.client-secret==//eth client secrete  takaychi 